const safeJson = (value) => JSON.stringify(value).replaceAll("<", "\\u003c");

export function renderWebApp(defaults) {
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>FOMO NoMo</title>
<script>
  window.va = window.va || function () { (window.vaq = window.vaq || []).push(arguments); };
</script>
<script defer src="/_vercel/insights/script.js"></script>
<style>
*{box-sizing:border-box}button,input{font:inherit}body{margin:0;background:#f1eee5;color:#20231d;font:15px/1.35 Arial,sans-serif}
button{cursor:pointer}.shell{min-height:100vh}.topbar{align-items:center;border-bottom:1px solid #b8b2a4;display:flex;gap:16px;justify-content:space-between;padding:13px 20px;position:sticky;top:0;background:#f1eee5eF;backdrop-filter:blur(12px);z-index:5}
.brand-group{align-items:baseline;display:flex;flex-wrap:wrap;gap:4px 11px}.brand{font:26px/1 Georgia,serif}.brand span{color:#68765f}.credit{color:#686b61;font-size:12px;text-decoration:underline;text-underline-offset:2px}.credit:hover{color:#20231d}.top-actions{align-items:center;display:flex;gap:10px}.status{color:#686b61;font-size:12px}.button{border:1px solid #20231d;background:transparent;border-radius:99px;padding:8px 14px}.button.primary{background:#20231d;color:#f8f5ec}.button:disabled{cursor:wait;opacity:.55}
.layout{display:grid;grid-template-columns:290px minmax(0,1fr);min-height:calc(100vh - 59px)}aside{border-right:1px solid #b8b2a4;padding:22px 18px}.side-head{display:flex;align-items:center;justify-content:space-between;margin-bottom:12px}.side-title{align-items:center;display:flex;gap:7px;position:relative}h2{font:25px/1.1 Georgia,serif;margin:0}.small-button{background:none;border:0;text-decoration:underline;text-underline-offset:3px}.info-button{align-items:center;background:transparent;border:1px solid #77766f;border-radius:50%;color:#62645c;display:inline-flex;font:700 10px/1 Arial,sans-serif;height:17px;justify-content:center;padding:0;width:17px}.info-tooltip{background:#20231d;color:#f8f5ec;display:none;font-size:11px;left:0;line-height:1.45;padding:10px 12px;position:absolute;top:34px;width:225px;z-index:8}.info-tooltip strong{display:block;margin-bottom:4px}.info-button:hover+.info-tooltip,.info-button:focus-visible+.info-tooltip{display:block}
.source{border-top:1px solid #c9c3b6;padding:12px 0}.source-row{align-items:center;display:flex;gap:8px}.source input[type=checkbox]{accent-color:#68765f}.source-name{font-weight:700;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.source-swatch{border:1px solid #777;border-radius:50%;flex:0 0 auto;height:15px;width:15px}.source-url{color:#686b61;font-size:11px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.source-type{background:#ddd7c9;border-radius:99px;color:#55594e;font-size:9px;letter-spacing:.08em;margin-left:auto;padding:3px 6px;text-transform:uppercase}.edit-source{background:none;border:0;font-size:11px;padding:2px;text-decoration:underline;text-underline-offset:2px}.remove{background:none;border:0;color:#8d4639;font-size:18px;padding:0 2px}.empty-sources{color:#686b61;font-size:12px;padding:12px 0}
.settings{border-top:1px solid #b8b2a4;margin-top:20px;padding-top:18px}.field{display:block;margin:0 0 12px}.field[hidden]{display:none}.field span{display:block;font-size:10px;font-weight:700;letter-spacing:.08em;margin-bottom:5px;text-transform:uppercase}.field input{background:#faf8f1;border:1px solid #b8b2a4;border-radius:4px;padding:8px;width:100%}.field input[type=color]{appearance:none;-webkit-appearance:none;border-radius:50%;cursor:pointer;height:40px;padding:3px;width:40px}.field input[type=color]::-webkit-color-swatch-wrapper{padding:0}.field input[type=color]::-webkit-color-swatch{border:0;border-radius:50%}.field input[type=color]::-moz-color-swatch{border:0;border-radius:50%}.provider-note{color:#686b61;font-size:10px;margin:14px 0 0}
.content{min-width:0;padding:28px 22px 60px}.hero{align-items:end;display:flex;gap:20px;justify-content:space-between;margin-bottom:22px}.hero h1{font:clamp(38px,6vw,72px)/.94 Georgia,serif;letter-spacing:-.04em;margin:8px 0}.hero p{color:#686b61;margin:0}.calendar{background:#faf8f1;border-collapse:collapse;table-layout:fixed;width:100%}.calendar th{background:#20231d;color:#f8f5ec;font-size:10px;letter-spacing:.08em;padding:8px;text-transform:uppercase}.calendar td{border:1px solid #b8b2a4;height:165px;padding:7px;vertical-align:top}.calendar td.today{background:#fff3bd}.day-number{font:15px Georgia,serif;margin-bottom:6px}.event{background:var(--source-tint,#e1dccf);border-left:4px solid var(--source-color,#68765f);margin-bottom:6px;padding:6px}.event-time,.event-meta{color:#4f5349;font-size:9px}.event-title{font:13px/1.15 Georgia,serif;margin:3px 0}.event-title a{color:inherit;text-decoration-thickness:1px;text-underline-offset:2px}.empty-day{color:#999488;font-size:9px;font-style:italic}.message{border:1px dashed #9e998c;color:#686b61;padding:30px;text-align:center}.agenda{display:none}.error{color:#8d4639}
.dialog{background:#f8f5ec;border:1px solid #20231d;box-shadow:0 15px 60px #0003;max-width:500px;padding:24px;width:calc(100% - 28px)}dialog::backdrop{background:#20231d99}.dialog h2{margin-bottom:18px}.dialog-actions{display:flex;gap:8px;justify-content:flex-end;margin-top:18px}
@media(max-width:900px){.layout{display:block}aside{border-bottom:1px solid #b8b2a4;border-right:0}.content{padding:24px 14px 50px}.calendar{display:none}.agenda{display:block}.agenda-day{border-top:1px solid #b8b2a4;padding:16px 0}.agenda-day h3{font:22px Georgia,serif;margin:0 0 10px}.event{padding:10px}.event-title{font-size:18px}.event-time,.event-meta{font-size:11px}.topbar{padding:12px 14px}.status{display:none}}
</style></head><body><div class="shell">
<nav class="topbar"><div class="brand-group"><div class="brand">FOMO <span>NoMo</span></div><a class="credit" href="https://funplings.github.io/" target="_blank" rel="noopener">created by funplings</a></div><div class="top-actions"><span class="status" id="status">Your settings stay in this browser</span><button class="button primary" id="refresh">Refresh events</button></div></nav>
<div class="layout"><aside><div class="side-head"><div class="side-title"><h2>Sources</h2><button class="info-button" aria-describedby="sources-tooltip" aria-label="Supported source types">i</button><div class="info-tooltip" id="sources-tooltip" role="tooltip"><strong>Supported sources</strong>Square classes, Luma calendars, Partiful profiles, and Eventbrite organizers.</div></div><button class="small-button" id="add-source">+ Add</button></div><div id="sources"></div>
<div class="settings"><h2>Settings</h2><label class="field"><span>Days ahead</span><input id="days" type="number" min="1" max="60"></label></div>
<p class="provider-note">Settings are stored only in localStorage.</p></aside>
<main class="content"><div class="hero"><div><h1>What's Happening?</h1><p id="summary"></p></div></div><div id="calendar"><div class="message">Loading your calendar...</div></div></main></div></div>
<dialog class="dialog" id="source-dialog"><form method="dialog" id="source-form"><h2 id="source-dialog-title">Add a source</h2><label class="field"><span>Name</span><input id="source-name" placeholder="Recess Grove" required></label><label class="field" id="source-url-field"><span>Public source URL</span><input id="source-url" type="url" placeholder="https://..." required><small class="provider-note">Supported: Luma calendars, Square classes, Partiful profiles, Eventbrite organizers.</small></label><label class="field"><span>Color</span><input id="source-color" type="color"></label><div class="dialog-actions"><button class="button" id="source-cancel" type="button">Cancel</button><button class="button primary" id="source-save" value="default">Add source</button></div></form></dialog>
<script>const DEFAULTS=${safeJson(defaults)};
const KEY="fomo-nomo-settings-v1",LEGACY_KEY="open-calendar-settings-v1",PALETTE=["#d97757","#6688c5","#9b72b0","#5f9b72","#d0a43c","#b85c7a","#4e9ca1","#8b795e"];let state=loadState(),events=[],editingSourceIndex=null;
const $=(id)=>document.getElementById(id);const esc=(v="")=>String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function validColor(color,index=0){return /^#[0-9a-f]{6}$/i.test(color||"")?color:PALETTE[index%PALETTE.length]}
function tint(color){const c=validColor(color);return c+"35"}
function hydrate(value){value.sources=(value.sources||[]).map((source,index)=>({...source,color:validColor(source.color,index)}));return value}
function loadState(){try{return hydrate(JSON.parse(localStorage.getItem(KEY)||localStorage.getItem(LEGACY_KEY))||structuredClone(DEFAULTS))}catch{return hydrate(structuredClone(DEFAULTS))}}
function save(){localStorage.setItem(KEY,JSON.stringify(state));renderSources();renderHeader()}
function typeFor(url){if(url.includes("squareup.com"))return"square";if(url.includes("partiful.com"))return"partiful";if(url.includes("eventbrite.com"))return"eventbrite";if(url.includes("luma.com"))return"luma";return"web"}
function renderSources(){const host=$("sources");host.innerHTML="";if(!state.sources.length){host.innerHTML='<div class="empty-sources">No sources yet. Add a Luma, Square, Partiful, or Eventbrite link to begin.</div>';return}state.sources.forEach((source,index)=>{const el=document.createElement("div");el.className="source";el.innerHTML='<div class="source-row"><input type="checkbox" '+(source.enabled!==false?"checked":"")+'><span class="source-swatch" style="background:'+validColor(source.color,index)+'"></span><span class="source-name">'+esc(source.name)+'</span><span class="source-type">'+typeFor(source.url)+'</span><button class="edit-source">Edit</button><button class="remove" title="Remove source">×</button></div><div class="source-url">'+esc(source.url)+'</div>';const [check,,,,edit,remove]=el.querySelector(".source-row").children;check.onchange=()=>{source.enabled=check.checked;save()};edit.onclick=()=>openSourceDialog(index);remove.onclick=()=>{state.sources.splice(index,1);save();refresh()};host.append(el)})}
function renderHeader(){const p=state.preferences;$("summary").textContent=events.length+" events in the next "+p.lookaheadDays+" days.";$("days").value=p.lookaheadDays}
const dayKey=d=>[d.getFullYear(),String(d.getMonth()+1).padStart(2,"0"),String(d.getDate()).padStart(2,"0")].join("-");const time=d=>d.toLocaleTimeString("en-US",{hour:"numeric",minute:"2-digit"});
function eventHtml(e){const source=state.sources.find(source=>source.id===e.sourceId),color=validColor(source?.color);return '<div class="event" style="--source-color:'+color+';--source-tint:'+tint(color)+'"><div class="event-time">'+time(new Date(e.start))+(e.categories[0]?" · "+esc(e.categories[0]):"")+'</div><div class="event-title"><a href="'+esc(e.url)+'" target="_blank" rel="noopener">'+esc(e.title)+'</a></div><div class="event-meta">'+esc(e.venue)+(e.price?" · "+esc(e.price):"")+'</div></div>'}
function renderCalendar(){renderHeader();const root=$("calendar");if(!events.length){root.innerHTML='<div class="message">No upcoming events found. Add a source or extend your date range.</div>';return}const grouped=new Map;events.sort((a,b)=>new Date(a.start)-new Date(b.start)).forEach(e=>{const k=dayKey(new Date(e.start));grouped.set(k,[...(grouped.get(k)||[]),e])});const start=new Date;start.setHours(0,0,0,0);start.setDate(start.getDate()-start.getDay());const end=new Date;end.setDate(end.getDate()+Number(state.preferences.lookaheadDays));end.setDate(end.getDate()+(6-end.getDay()));const days=[];for(const d=new Date(start);d<=end;d.setDate(d.getDate()+1))days.push(new Date(d));const today=dayKey(new Date);let rows="";for(let i=0;i<days.length;i+=7)rows+="<tr>"+days.slice(i,i+7).map(d=>{const es=grouped.get(dayKey(d))||[];return '<td class="'+(dayKey(d)===today?"today":"")+'"><div class="day-number">'+d.toLocaleDateString("en-US",{month:"short",day:"numeric"})+'</div>'+(es.map(eventHtml).join("")||'<div class="empty-day">No events</div>')+"</td>"}).join("")+"</tr>";const table='<table class="calendar"><thead><tr>'+["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].map(x=>"<th>"+x+"</th>").join("")+"</tr></thead><tbody>"+rows+"</tbody></table>";const agenda='<div class="agenda">'+days.filter(d=>grouped.has(dayKey(d))).map(d=>'<section class="agenda-day"><h3>'+d.toLocaleDateString("en-US",{weekday:"long",month:"long",day:"numeric"})+'</h3>'+(grouped.get(dayKey(d))||[]).map(eventHtml).join("")+"</section>").join("")+"</div>";root.innerHTML=table+agenda}
async function refresh(){const button=$("refresh"),status=$("status");button.disabled=true;button.textContent="Refreshing...";status.className="status";status.textContent="Fetching public sources";try{const response=await fetch("/api/events",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(state)});const data=await response.json();if(!response.ok)throw new Error(data.error||"Could not refresh events.");events=data.events||[];renderCalendar();status.textContent=data.failures?.length?data.failures.length+" source failed to load":"Updated just now"}catch(error){status.className="status error";status.textContent=error.message;$("calendar").innerHTML='<div class="message error">'+esc(error.message)+"</div>"}finally{button.disabled=false;button.textContent="Refresh events"}}
function openSourceDialog(index=null){editingSourceIndex=index;const editing=index!==null,source=editing?state.sources[index]:null;$("source-dialog-title").textContent=editing?"Edit source":"Add a source";$("source-save").textContent=editing?"Save changes":"Add source";$("source-url-field").hidden=editing;$("source-url").required=!editing;$("source-name").value=source?.name||"";$("source-url").value=source?.url||"";$("source-color").value=source?.color||PALETTE[state.sources.length%PALETTE.length];$("source-dialog").showModal()}
$("source-cancel").onclick=()=>{$("source-dialog").close();$("source-form").reset();editingSourceIndex=null};$("add-source").onclick=()=>openSourceDialog();$("source-form").onsubmit=e=>{e.preventDefault();const name=$("source-name").value.trim(),color=$("source-color").value;if(editingSourceIndex!==null){state.sources[editingSourceIndex].name=name;state.sources[editingSourceIndex].color=color;$("source-dialog").close();save();renderCalendar();return}const url=$("source-url").value.trim();state.sources.push({id:"custom-"+Date.now(),name,url,color,enabled:true,categories:[]});$("source-dialog").close();e.target.reset();save();refresh()};
$("days").onchange=()=>{state.preferences.lookaheadDays=Math.min(60,Math.max(1,Number($("days").value)||14));save();refresh()};$("refresh").onclick=refresh;renderSources();renderHeader();refresh();
</script>
<script type="module">
import { inject } from 'https://cdn.jsdelivr.net/npm/@vercel/analytics@1/dist/index.js';
inject();
</script>
</body></html>`;
}
